---

<br>

## Capstone_Project_Missing_Values

<br>

In [434]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
import math as math

In [435]:
df = pd.read_csv('df1_clean_last.csv')

In [436]:
df1 = df.copy()

In [437]:
df2 = df.copy()

In [438]:
df3 = df1.copy()

In [439]:
df4 = df1.copy()

In [440]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,15909,15910,15911,15912,15913,15914,15915,15916,15917,15918
Body_Type,Sedans,Sedans,Sedans,Sedans,Sedans,Sedans,Station wagon,Compact,Sedans,Sedans,...,Van,Van,Van,Van,Van,Van,Van,Van,Van,Van
Price,15770,14500,14640,14500,16790,15090,16422,14480,16700,17990,...,39990,39980,39980,39950,39950,39950,39885,39875,39700,40999
Vat,VAT deductible,Price negotiable,VAT deductible,NaN,NaN,NaN,VAT deductible,VAT deductible,NaN,NaN,...,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible,VAT deductible
Km,56013,80000,83450,73000,16200,63668,62111,14986,57000,16103,...,3500,8500,100,-,1000,-,9900,15,10,-
Previous_Owner,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,...,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0
kW,66.0,141.0,85.0,66.0,66.0,85.0,85.0,66.0,85.0,70.0,...,147.0,165.0,118.0,147.0,165.0,147.0,165.0,146.0,147.0,165.0
Condition,Used,Used,Used,Used,Used,Used,Used,Used,Used,Used,...,Demonstration,Demonstration,Pre-registered,New,Demonstration,New,Used,Pre-registered,Pre-registered,Demonstration
Make,Audi,Audi,Audi,Audi,Audi,Audi,Audi,Audi,Audi,Audi,...,Renault,Renault,Renault,Renault,Renault,Renault,Renault,Renault,Renault,Renault
Model,A1,A1,A1,A1,A1,A1,A1,A1,A1,A1,...,Espace,Espace,Espace,Espace,Espace,Espace,Espace,Espace,Espace,Espace
Registration_Year,2016.0,2017.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2016.0,2017.0,...,2019.0,2019.0,2019.0,NaN,2019.0,NaN,2019.0,2019.0,2019.0,2019.0
Body_Color,Black,Red,Black,Brown,Black,White,White,Red,Grey,White,...,Black,Blue,White,Black,White,Grey,Grey,White,Grey,Grey
Paint_Type,Metallic,NaN,Metallic,Metallic,Metallic,Metallic,Metallic,Metallic,Metallic,NaN,...,Metallic,Metallic,Metallic,Metallic,Metallic,Metallic,Metallic,NaN,NaN,Metallic
Upholstery,"Cloth, Black","Cloth, Grey","Cloth, Black",NaN,"Cloth, Black","Part leather, Black","Part leather, Black","Cloth, Black","Cloth, Grey",NaN,...,NaN,"Full leather, Other","Full leather, Grey",NaN,"Full leather, Brown",NaN,Cloth,"Full leather, Black",Part leather,"Full leather, Brown"
Nr_of_Doors,5.0,3.0,4.0,3.0,5.0,4.0,4.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
Nr_of_Seats,5.0,4.0,4.0,4.0,5.0,5.0,5.0,5.0,4.0,4.0,...,5.0,5.0,7.0,5.0,7.0,5.0,5.0,7.0,7.0,5.0
Gearing_Type,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,...,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic,Automatic
Displacement,1422.0,1798.0,1598.0,1422.0,1422.0,1598.0,1598.0,1422.0,1598.0,999.0,...,1997.0,1798.0,1598.0,1997.0,1798.0,1997.0,1798.0,1997.0,1997.0,1798.0
Cylinders,3.0,4.0,NaN,3.0,3.0,NaN,4.0,NaN,4.0,NaN,...,NaN,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
Drive_Chain,front,front,front,NaN,front,NaN,front,front,front,NaN,...,NaN,front,NaN,front,front,front,front,front,front,4WD
Fuel,Diesel,Gasoline,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Diesel,Gasoline,...,Diesel,Gasoline,Diesel,Diesel,Gasoline,Diesel,Gasoline,Diesel,Diesel,Gasoline
CO2_Emission,99.0,129.0,99.0,99.0,109.0,9.0,98.0,97.0,97.0,NaN,...,NaN,153.0,123.0,139.0,153.0,139.0,168.0,139.0,139.0,153.0
Emission_Class,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6,Euro 6,NaN,...,NaN,Euro 6,Euro 6,NaN,Euro 6,NaN,NaN,Euro 6d-TEMP,Euro 6,Euro 6
Comfort_Convenience,"Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Hil...","Air conditioning,Cruise control,Electrical sid...","Air suspension,Armrest,Auxiliary heating,Elect...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Armrest,Electrical side mirro...","Air conditioning,Power windows",NaN,...,"Air conditioning,Automatic climate control,Cru...","Air conditioning,Automatic climate control,Cru...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Cru...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Cru...","Air conditioning,Automatic climate control,Cru...","Air conditioning,Armrest,Automatic climate con...","Air conditioning,Automatic climate control,Cru...","Air conditioning,Automatic climate control,Cru..."
Entertainment_Media,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","MP3,On-board computer","Bluetooth,CD player,Hands-free equipment,MP3,O...","Bluetooth,CD player,Hands-free equipment,MP3,O...","Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,CD player,Hands-free equipment,On-bo...","CD player,MP3,Radio",Radio,NaN,...,"Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Digital radio,Hands-free equipment,O...","Bluetooth,Digital radio,Hands-free equipment,O...","Bluetooth,Digital radio,Hands-free equipment,M...","Bluetooth,Digital radio,Hands-free equipment,O...","Bluetooth,Digital radio,Hands-free equipment,R...","Bluetooth,Hands-free equipment,On-board comput...","Bluetooth,Digital radio,Radio,USB",USB
Extras,"Alloy wheels,Catalytic Converter,Voice Control","Alloy wheels,Sport seats,Sport suspension,Voic...","Alloy wheels,Voice Control","Alloy wheels,Sport seats,Voice Control","Alloy wheels,Sport package,Sport suspension,Vo...","Alloy wheels,Sport package,Sport seats,Sport s...","Alloy wheels,Sport package,Sport seats,Sport s...",Alloy wheels,Alloy wheels,NaN,...,"Alloy wheels,Touch screen",Alloy wheels,"Alloy wheels,Touch screen,Voice Control","Alloy wheels,Touch screen","Alloy wheels,Catalytic Converter,Sport suspens...","Alloy wheels,Touch screen","Alloy wheels,Touch screen,Voice Control",Alloy wheels,"Alloy wheels,Touch screen","Alloy wheels,Touch screen"
Safety_Security,"ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Central door lock with r...","ABS,Central door lock,Daytime running lights,D...","ABS,Alarm system,Central door lock with remote...","ABS,Central door lock,Driver-side airbag,Elect...","ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Daytime running lights,D...","ABS,Central door lock,Driver-side airbag,Elect...",NaN,...,"ABS,Blind spot monitor,Central door lock,Dayti...","ABS,Adaptive headlights,Central door lock,Dayt...","ABS,Adaptive Cruise Control,Central door lock,...","ABS,Central door lock,Central door lock with r...","ABS,Adaptive Cruise Control,Blind spot monitor...","ABS,Central door lock,Central door lock with r...","ABS,Adaptive Cruise Control,Blind spot monitor...","ABS,Adaptive Cruise Control,Blind spot monitor...","ABS,Blind spot monitor,Driver-side airbag,Elec...","ABS,Blind spot monitor,Daytime running lights,..."
Gears,NaN,7.0,NaN,6.0,NaN,NaN,NaN,7.0,7.0,7.0,...,7.0,7.0,NaN,6.0,NaN,6.0,7.0,6.0,6.0,NaN
Combined_Cons,3.8,5.6,3.8,3.8,4.1,3.5,3.7,3.7,3.7,NaN,...,NaN,6.0,4.7,5.3,6.8,5.3,NaN,5.3,5.3,6.8
City_Cons,4.3,7.1,4.4,4.3,4.6,4.3,4.3,4.2,4.3,NaN,...,NaN,8.0,5.1,6.2,8.7,6.2,7.0,6.2,6.2,8.7
Highway_Cons,3.5,4.7,3.4,3.5,3.8,3.1,3.4,3.4,3.4,NaN,...,NaN,5.0,4.4,4.7,5.7,4.7,NaN,4.7,4.7,5.7

<br>

In [441]:
df1.isnull().sum()

Body_Type                60
Price                     0
Vat                    4513
Km                        0
Previous_Owner         6828
kW                       88
Condition                 2
Make                      0
Model                     0
Registration_Year      1597
Body_Color              597
Paint_Type             5772
Upholstery             3720
Nr_of_Doors             212
Nr_of_Seats             977
Gearing_Type              0
Displacement            496
Cylinders              5680
Drive_Chain            6858
Fuel                      0
CO2_Emission           2436
Emission_Class         3628
Comfort_Convenience     920
Entertainment_Media    1374
Extras                 2962
Safety_Security         982
Gears                  4712
Combined_Cons          2883
City_Cons              2422
Highway_Cons           3212
dtype: int64

In [442]:
df_old = pd.read_json('scout_car.json',lines = True )

In [443]:
df_old

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,...,"[\n, Sicherheit:, , Deaktivierung für Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,...,[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,...,"[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,...,"[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,...,"[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [444]:
df1.groupby(['Make','Model']).Body_Type.value_counts(dropna = False)

Make     Model     Body_Type
Audi     A1        Sedans           1538
                   Compact          1039
                   Station wagon      21
                   Other              13
                   Coupe               2
                   Van                 1
         A2        Off-Road            1
         A3        Sedans           2598
                   Station wagon     282
                   Compact           182
                   Other              16
                   Convertible         8
                   NaN                 7
                   Coupe               4
Opel     Astra     Station wagon    1211
                   Sedans           1053
                   Compact           185
                   Other              67
                   NaN                 7
                   Coupe               2
                   Off-Road            1
         Corsa     Compact          1230
                   Sedans            875
                   Other              87
                   Coupe              13
                   Transporter         7
                   Off-Road            3
                   NaN                 2
                   Van                 2
         Insignia  Station wagon    1611
                   Sedans            900
                   Other              48
                   Compact            27
                   Off-Road            7
                   NaN                 3
                   Coupe               1
                   Van                 1
Renault  Clio      Sedans            918
                   Compact           484
                   Station wagon     337
                   Other              51
                   Transporter        29
                   NaN                15
                   Off-Road            2
                   Van                 2
                   Coupe               1
         Duster    Off-Road           34
         Espace    Van               777
                   Station wagon      91
                   Transporter        52
                   NaN                26
                   Sedans             21
                   Off-Road            8
                   Other               8
                   Compact             6
                   Coupe               2
Name: Body_Type, dtype: int64

In [445]:
list(df1[df1.Body_Type.isnull()]['Model'].unique())

['A3', 'Astra', 'Corsa', 'Insignia', 'Clio', 'Espace']

In [446]:
null_models = list(df1[df1.Body_Type.isnull()]['Model'].unique())

In [447]:
for i in null_models:
    null_model_indexes = df1[(df1.Model == i) & (df1.Body_Type.isnull())].Body_Type.index
    my_mode = df1[(df1.Model == i)].Body_Type.mode()
    df1.Body_Type.iloc[null_model_indexes]= df1.Body_Type.iloc[null_model_indexes].fillna(my_mode[0])
    print(df1[df1.Body_Type.isnull()].value_counts())

Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)

C:\Users\gulfa\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [449]:
df1.groupby(['Make','Model']).Body_Type.value_counts(dropna = False)

Make     Model     Body_Type
Audi     A1        Sedans           1538
                   Compact          1039
                   Station wagon      21
                   Other              13
                   Coupe               2
                   Van                 1
         A2        Off-Road            1
         A3        Sedans           2605
                   Station wagon     282
                   Compact           182
                   Other              16
                   Convertible         8
                   Coupe               4
Opel     Astra     Station wagon    1218
                   Sedans           1053
                   Compact           185
                   Other              67
                   Coupe               2
                   Off-Road            1
         Corsa     Compact          1232
                   Sedans            875
                   Other              87
                   Coupe              13
                   Transporter         7
                   Off-Road            3
                   Van                 2
         Insignia  Station wagon    1614
                   Sedans            900
                   Other              48
                   Compact            27
                   Off-Road            7
                   Coupe               1
                   Van                 1
Renault  Clio      Sedans            933
                   Compact           484
                   Station wagon     337
                   Other              51
                   Transporter        29
                   Off-Road            2
                   Van                 2
                   Coupe               1
         Duster    Off-Road           34
         Espace    Van               803
                   Station wagon      91
                   Transporter        52
                   Sedans             21
                   Off-Road            8
                   Other               8
                   Compact             6
                   Coupe               2
Name: Body_Type, dtype: int64

<br>

- if the previous owner is null and the km == '-'   --> convert the km --> 0

<br>

In [456]:
null_km_po_indexes = df1[(df1.Previous_Owner.isnull())& (df1.Km == '-') & (df1.Condition == 'New')].Km.index
df1.Km.iloc[null_km_po_indexes] = df1.Km.iloc[null_km_po_indexes].replace('-','0')

In [457]:
df1[(df1.Previous_Owner.isnull())& (df1.Km == "0")].Km

734      0
743      0
869      0
946      0
977      0
        ..
15888    0
15890    0
15902    0
15912    0
15914    0
Name: Km, Length: 860, dtype: object

In [460]:
km_drop_index = df1[(df1.Km == '-')].index

In [461]:
df1.drop(km_drop_index, axis = 0, inplace = True)

In [462]:
df1[(df1.Km == '-')].index

Int64Index([], dtype='int64')

In [465]:
df1[df1.Condition == 'New'].Previous_Owner.value_counts(dropna= False)

NaN    1635
1.0       7
Name: Previous_Owner, dtype: int64

In [466]:
df2 = df1.copy()

In [470]:
condition_new_index = df2[(df2.Condition == 'New')].index
df2.Previous_Owner.loc[condition_new_index] = df2.Previous_Owner.loc[condition_new_index].replace(np.nan,0)

C:\Users\gulfa\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [471]:
df2.Previous_Owner.loc[condition_new_index]

122      0.0
710      0.0
734      0.0
741      0.0
743      0.0
        ...
15892    0.0
15902    0.0
15907    0.0
15912    0.0
15914    0.0
Name: Previous_Owner, Length: 1642, dtype: float64

In [472]:
condition_new_index = df2[(df2.Condition == 'New')].index
df2.Previous_Owner.loc[condition_new_index] = df2.Previous_Owner.loc[condition_new_index].replace(1,0)

In [476]:
df2[df.Condition == 'New'].Previous_Owner.value_counts(dropna = False)

<ipython-input-476-d3992107306c>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2[df.Condition == 'New'].Previous_Owner.value_counts(dropna = False)

0.0    1642
Name: Previous_Owner, dtype: int64

In [477]:
df1.Previous_Owner = df2.Previous_Owner

In [479]:
df1[df.Condition == 'New'].Previous_Owner.value_counts(dropna = False)

<ipython-input-479-5c497841619e>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df1[df.Condition == 'New'].Previous_Owner.value_counts(dropna = False)

0.0    1642
Name: Previous_Owner, dtype: int64

In [480]:
df2 = df1.copy()

In [485]:
df2[df2.Km == '0'].Previous_Owner.value_counts(dropna = False)

0.0    860
Name: Previous_Owner, dtype: int64

In [488]:
df2.Previous_Owner.value_counts(dropna = False)

1.0    8230
NaN    5067
0.0    1642
2.0     778
3.0      17
4.0       2
Name: Previous_Owner, dtype: int64

In [490]:
df1.drop('Vat', axis = 1, inplace = True)

In [491]:
df1.drop('CO2_Emission', axis = 1, inplace = True)
df1.drop('Emission_Class', axis = 1, inplace = True)

In [497]:
df1.drop('Previous_Owner', axis = 1, inplace = True)

In [498]:
df2 = df1.copy()

In [499]:
df1.isnull().sum()

Body_Type                 0
Price                     0
Km                        0
kW                       88
Condition                 1
Make                      0
Model                     0
Registration_Year      1586
Body_Color              592
Paint_Type             5715
Upholstery             3660
Nr_of_Doors             211
Nr_of_Seats             961
Gearing_Type              0
Displacement            483
Cylinders              5623
Drive_Chain            6805
Fuel                      0
Comfort_Convenience     908
Entertainment_Media    1356
Extras                 2907
Safety_Security         970
Gears                  4674
Combined_Cons          2830
City_Cons              2372
Highway_Cons           3156
dtype: int64

In [502]:
df1[df1.Model == 'A1'].kW.value_counts()

85.0     883
70.0     790
66.0     462
92.0     172
60.0     156
71.0      56
110.0     30
141.0     16
147.0     14
67.0      12
87.0       4
93.0       3
140.0      1
86.0       1
112.0      1
Name: kW, dtype: int64

In [509]:
df1[df1.kW.isnull()].groupby(['Model']).kW.value_counts(dropna = False)

Model     kW
A1        NaN     2
A3        NaN     1
Astra     NaN     2
Clio      NaN    29
Corsa     NaN     2
Duster    NaN     8
Espace    NaN    34
Insignia  NaN    10
Name: kW, dtype: int64

In [514]:
null_models = list(df1[df1.kW.isnull()].Model.unique())

In [516]:
for i in null_models:
    null_model_indexes = df1[(df1.Model == i) & (df1.kW.isnull())].kW.index
    my_mode = df1[(df1.Model == i)].kW.mode()
    df1.kW.loc[null_model_indexes]= df1.kW.loc[null_model_indexes].fillna(my_mode[0])
    print(df1[df1.kW.isnull()].value_counts())

Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)

In [517]:
df1[df1.kW.isnull()]

Empty DataFrame
Columns: [Body_Type, Price, Km, kW, Condition, Make, Model, Registration_Year, Body_Color, Paint_Type, Upholstery, Nr_of_Doors, Nr_of_Seats, Gearing_Type, Displacement, Cylinders, Drive_Chain, Fuel, Comfort_Convenience, Entertainment_Media, Extras, Safety_Security, Gears, Combined_Cons, City_Cons, Highway_Cons]
Index: []

[0 rows x 26 columns]

In [518]:
df1.isna().sum()

Body_Type                 0
Price                     0
Km                        0
kW                        0
Condition                 1
Make                      0
Model                     0
Registration_Year      1586
Body_Color              592
Paint_Type             5715
Upholstery             3660
Nr_of_Doors             211
Nr_of_Seats             961
Gearing_Type              0
Displacement            483
Cylinders              5623
Drive_Chain            6805
Fuel                      0
Comfort_Convenience     908
Entertainment_Media    1356
Extras                 2907
Safety_Security         970
Gears                  4674
Combined_Cons          2830
City_Cons              2372
Highway_Cons           3156
dtype: int64

In [532]:
df1[df1.Condition.isnull()].Condition.index

2765

In [535]:
df1.Condition.loc[df1[df1.Condition.isnull()].Condition.index] = df1.Condition.loc[df1[df1.Condition.isnull()].Condition.index].replace(np.nan,'Used')

In [536]:
df1[df1.Condition.isnull()].Condition

Series([], Name: Condition, dtype: object)

In [537]:
df1.Condition.loc[df1[df1.Condition.isnull()].Condition.index]

Series([], Name: Condition, dtype: object)

In [538]:
df1.isna().sum()

Body_Type                 0
Price                     0
Km                        0
kW                        0
Condition                 0
Make                      0
Model                     0
Registration_Year      1586
Body_Color              592
Paint_Type             5715
Upholstery             3660
Nr_of_Doors             211
Nr_of_Seats             961
Gearing_Type              0
Displacement            483
Cylinders              5623
Drive_Chain            6805
Fuel                      0
Comfort_Convenience     908
Entertainment_Media    1356
Extras                 2907
Safety_Security         970
Gears                  4674
Combined_Cons          2830
City_Cons              2372
Highway_Cons           3156
dtype: int64

In [539]:
df2[df2.Condition.isnull()].Condition

2765    NaN
Name: Condition, dtype: object

In [554]:
null_models = list(df1[df1.Body_Color.isnull()].Model.unique())

In [555]:
for i in null_models:
    null_model_indexes = df1[(df1.Model == i) & (df1.Body_Color.isnull())].Body_Color.index
    my_mode = df1[(df1.Model == i)].Body_Color.mode()
    df1.Body_Color.loc[null_model_indexes]= df1.Body_Color.loc[null_model_indexes].fillna(my_mode[0])
    print(df1[df1.Body_Color.isnull()].value_counts())

Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)

C:\Users\gulfa\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [556]:
df1[df1.Body_Color.isnull()]

Empty DataFrame
Columns: [Body_Type, Price, Km, kW, Condition, Make, Model, Registration_Year, Body_Color, Paint_Type, Upholstery, Nr_of_Doors, Nr_of_Seats, Gearing_Type, Displacement, Cylinders, Drive_Chain, Fuel, Comfort_Convenience, Entertainment_Media, Extras, Safety_Security, Gears, Combined_Cons, City_Cons, Highway_Cons]
Index: []

[0 rows x 26 columns]

In [557]:
df1.isna().sum()

Body_Type                 0
Price                     0
Km                        0
kW                        0
Condition                 0
Make                      0
Model                     0
Registration_Year      1586
Body_Color                0
Paint_Type             5715
Upholstery             3660
Nr_of_Doors             211
Nr_of_Seats             961
Gearing_Type              0
Displacement            483
Cylinders              5623
Drive_Chain            6805
Fuel                      0
Comfort_Convenience     908
Entertainment_Media    1356
Extras                 2907
Safety_Security         970
Gears                  4674
Combined_Cons          2830
City_Cons              2372
Highway_Cons           3156
dtype: int64

In [558]:
df2 = df1.copy()

In [559]:
df1.Paint_Type.unique()

array(['Metallic', nan, 'Uni/basic', 'Perl effect'], dtype=object)

In [562]:
null_models = list(df1[df1.Paint_Type.isnull()].Model.unique())

In [563]:
for i in null_models:
    null_model_indexes = df1[(df1.Model == i) & (df1.Paint_Type.isnull())].Paint_Type.index
    my_mode = df1[(df1.Model == i)].Paint_Type.mode()
    df1.Paint_Type.loc[null_model_indexes]= df1.Paint_Type.loc[null_model_indexes].fillna(my_mode[0])
    print(df1[df1.Paint_Type.isnull()].value_counts())

Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)

C:\Users\gulfa\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [564]:
df1[df1.Paint_Type.isnull()]

Empty DataFrame
Columns: [Body_Type, Price, Km, kW, Condition, Make, Model, Registration_Year, Body_Color, Paint_Type, Upholstery, Nr_of_Doors, Nr_of_Seats, Gearing_Type, Displacement, Cylinders, Drive_Chain, Fuel, Comfort_Convenience, Entertainment_Media, Extras, Safety_Security, Gears, Combined_Cons, City_Cons, Highway_Cons]
Index: []

[0 rows x 26 columns]