# Capstone Project

## EDA for Car Price Prediction Model

---

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [4]:
df = pd.read_json('scout_car.json', lines=True)

In [7]:
df.sample(10)

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
1027,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,"Sportback 1.0 TFSI ultra S-Line sport Navi, Xe...",Compact,20685,VAT deductible,"6,200 km",06/2018,1 previous owner,NaN,...,"[\n, Technik & Sicherheit:, Außenspiegel elekt...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
11063,https://www.autoscout24.com//offers/opel-insig...,Opel Insignia,ST 1.6 CDTI Business Edition/NAV/TEMPO/,Station wagon,12750,VAT deductible,"75,709 km",03/2016,1 previous owner,NaN,...,"[\n, Fahrassistenz-Paket: , Tempomat, Lichtsen...",NaN,[\n6\n],[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
5865,https://www.autoscout24.com//offers/opel-astra...,Opel Astra,1.6 CDTi 5 porte Advance,Sedans,14900,None,"90,250 km",07/2016,1 previous owner,NaN,...,"[\nDEK:[1628434], La Opel Astra e' un'auto man...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,"Sportback 1.4 TFSI Navi, PDC, Shz, LM 17"", Klima,",Sedans,20985,VAT deductible,"14,300 km",02/2018,1 previous owner,NaN,...,"[\n, Highlights:, Anschlussgarantie 3 Jahre, m...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
12255,https://www.autoscout24.com//offers/opel-insig...,Opel Insignia,B 1.5 DiTurbo ST S&S Innov./Panoramad.,Station wagon,20750,VAT deductible,"29,420 km",01/2018,1 previous owner,NaN,...,"[\n, Fahrzeug steht in 14943 Luckenwalde, Schi...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
11742,https://www.autoscout24.com//offers/opel-insig...,Opel Insignia,Grand Sport 1.6 Diesel EDITION*AGR SITZE*KAMERA,Sedans,16980,VAT deductible,"3,500 km",05/2018,1 previous owner,NaN,...,"[\n, Ihre Angebots-Nr. für Anfragen: 44857-795...",NaN,[\n6\n],[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN
8788,https://www.autoscout24.com//offers/opel-corsa...,Opel Corsa,E 1.3 CDTI Edition Tempomat MFL Klima,Compact,6580,VAT deductible,"115,379 km",01/2016,1 previous owner,NaN,...,"[\n, Nr. 5349 Standort: 28279 Bremen , , , ...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1573,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,SPB 30 TFSI S tronic Admired,Sedans,23300,VAT deductible,10 km,05/2019,1 previous owner,NaN,...,"[\nDEK:[2526016], Cod. 56571-N, Vettura uffici...",NaN,[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
1795,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,SPB 1.6 TDI 116 CV Metal plus,Sedans,16900,VAT deductible,"20,951 km",06/2018,1 previous owner,NaN,...,"[\nVOLANTE MULTIFUNZIONE, AUDI A1 SPORTBACK 1....",NaN,[\n5\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
10171,https://www.autoscout24.com//offers/opel-corsa...,Opel Corsa,"1,4 Österreich Edition",Sedans,10740,None,10 km,04/2019,None,NaN,...,"[\nAktionspreis inklusive Eintausch-, Leasingb...",NaN,[\n5\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            15919 non-null  object
 1   make_model                     15919 non-null  object
 2   short_description              15873 non-null  object
 3   body_type                      15859 non-null  object
 4   price                          15919 non-null  int64
 5   vat                            11406 non-null  object
 6   km                             15919 non-null  object
 7   registration                   15919 non-null  object
 8   prev_owner                     9091 non-null   object
 9   kW                             0 non-null      float64
 10  hp                             15919 non-null  object
 11  Type                           15917 non-null  object
 12  Previous Owners                9279 non-null   object
 13  Next Inspection                3535 non-null   object
 14  Inspection new                 3932 non-null   object
 15  Warranty                       10499 non-null  object
 16  Full Service                   8215 non-null   object
 17  Non-smoking Vehicle            7177 non-null   object
 18  null                           15919 non-null  object
 19  Make                           15919 non-null  object
 20  Model                          15919 non-null  object
 21  Offer Number                   12744 non-null  object
 22  First Registration             14322 non-null  object
 23  Body Color                     15322 non-null  object
 24  Paint Type                     10147 non-null  object
 25  Body Color Original            12160 non-null  object
 26  Upholstery                     12199 non-null  object
 27  Body                           15859 non-null  object
 28  Nr. of Doors                   15707 non-null  object
 29  Nr. of Seats                   14942 non-null  object
 30  Model Code                     4978 non-null   object
 31  Gearing Type                   15919 non-null  object
 32  Displacement                   15423 non-null  object
 33  Cylinders                      10239 non-null  object
 34  Weight                         8945 non-null   object
 35  Drive chain                    9061 non-null   object
 36  Fuel                           15919 non-null  object
 37  Consumption                    14013 non-null  object
 38  CO2 Emission                   14111 non-null  object
 39  Emission Class                 12898 non-null  object
 40
Comfort & Convenience
        14999 non-null  object
 41
Entertainment & Media
        14545 non-null  object
 42
Extras
                       12957 non-null  object
 43
Safety & Security
            14937 non-null  object
 44  description                    15919 non-null  object
 45  Emission Label                 3985 non-null   object
 46  Gears                          11207 non-null  object
 47  Country version                7586 non-null   object
 48  Electricity consumption        137 non-null    object
 49  Last Service Date              566 non-null    object
 50  Other Fuel Types               880 non-null    object
 51  Availability                   635 non-null    object
 52  Last Timing Belt Service Date  16 non-null     object
 53  Available from                 272 non-null    object
dtypes: float64(1), int64(1), object(52)
memory usage: 6.6+ MB